apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  namespace: opentelemetrycollector
  name: mesh-default
spec:
  tracing:
  - providers:
    - name: otel
      randomSamplingPercentage: 100