apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
spec:
  finalizers:
  - kubernetes
---
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  version: v1.23.0
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  values:
    meshConfig:
      discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
    gateways:
      istio-ingressgateway:
        enabled: true
        namespace: ingress-gateway # Specify the namespace for the ingress gateway
        k8s:
          service:
            type: LoadBalancer # Use NodePort if LoadBalancer is unavailable
            ports:
            - name: http2
              port: 80
              targetPort: 80
            - name: https
              port: 443
              targetPort: 443
