apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  version: default
  istio_namespace: istio-system
  deployment:
    logger:
      log_level: info
    view_only_mode: false
  external_services:
    prometheus:
      url: "http://prometheus-operated.openshift-user-workload-monitoring.svc:9090"
