apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  finalizers:
    - maistra.io/istio-operator
  name: basic-control-plane
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    egress:
      runtime:
        container:
          resources:
            limits:
              cpu: 500m
      service: {}
    ingress:
      runtime:
        container:
          resources:
            limits:
              cpu: 500m
      service: {}
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  profiles:
    - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.5